apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - nodePort: 31245
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
